version: '2'
services:
#  app-zookeeper:
#    container_name: app-zookeeper
#    image: zookeeper:3.5
#    hostname: zkserver #容器名
#    restart: always
#    ports:
#      - 2181:2181
#    #volumes:
#    #  - /usr/local/docker_app/zookeeper/zoo1/data:/data
#    #  - /usr/local/docker_app/zookeeper/zoo1/datalog:/datalog

  app-dubbo:
    image: chenchuxin/dubbo-admin
    environment:
      - dubbo.registry.address=zookeeper://zkserver:2181
      - dubbo.admin.root.password=root
      - dubbo.admin.guest.password=guest
    restart: always
    ports:
      - 8090:8080 #主机端口：容器端口
