version: '2'
services:
  app-mysql:
    container_name: app-mysql
    image: mysql:5.6.21
    restart: always
    hostname: dbserver
    ports:
      - 3306:3306
    volumes:
      - ./../mysql/data:/var/lib/mysql
      - ./../mysql/conf:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: user123

