version: '2'
services:
  app-nginx:
    container_name: app-nginx
    image: nginx:1.15
    restart: always
    ports:
      - 80:80
      - 443:443
      - 1000:1000
      - 1001:1001
      - 1002:1002
    volumes:
      - ./../nginx/conf.d:/etc/nginx/conf.d